# Generated by Django 3.0.14 on 2021-07-25 16:29

import attendence_sys.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faculty_Name', models.CharField(blank=True, max_length=200, null=True)),
                ('Student_ID', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('time', models.TimeField(auto_now_add=True, null=True)),
                ('branch', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=200, null=True)),
                ('section', models.CharField(max_length=200, null=True)),
                ('period', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(default='Absent', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_id', models.CharField(max_length=200, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('course', models.CharField(choices=[('BSc Agriculture (Economics Option)', 'BSc Agriculture (Economics Option)'), ('BSc Agriculture (Extension Option)', 'BSc Agriculture (Extension Option)'), ('BSc Agribusiness Management', 'BSc Agribusiness Management')], max_length=100, null=True)),
                ('year', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=100, null=True)),
                ('faculty', models.CharField(choices=[('Faculty of Agriculture', 'Faculty of Agriculture'), ('Faculty of Renewable Natural Resources', 'Faculty of Renewable Natural Resources'), ('Faculty of Built Environment', 'Faculty of Built Environment')], max_length=100, null=True)),
                ('department', models.CharField(choices=[('Department of Agricultural Economics, Agribusiness and Extension', 'Department of Agricultural Economics, Agribusiness and Extension'), ('Department of Animal Science', 'Department of Animal Science'), ('Department of Horticulture', 'Department of Horticulture')], max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=attendence_sys.models.student_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('firstname', models.CharField(max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('registration_id', models.CharField(max_length=200, null=True)),
                ('course', models.CharField(choices=[('BSc Agriculture (Economics Option)', 'BSc Agriculture (Economics Option)'), ('BSc Agriculture (Extension Option)', 'BSc Agriculture (Extension Option)'), ('BSc Agribusiness Management', 'BSc Agribusiness Management')], max_length=100, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('faculty', models.CharField(choices=[('Faculty of Agriculture', 'Faculty of Agriculture'), ('Faculty of Renewable Natural Resources', 'Faculty of Renewable Natural Resources'), ('Faculty of Built Environment', 'Faculty of Built Environment')], max_length=100, null=True)),
                ('department', models.CharField(choices=[('Department of Agricultural Economics, Agribusiness and Extension', 'Department of Agricultural Economics, Agribusiness and Extension'), ('Department of Animal Science', 'Department of Animal Science'), ('Department of Horticulture', 'Department of Horticulture')], max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=attendence_sys.models.student_directory_path)),
                ('about', models.TextField(blank=True, max_length=500, verbose_name='about')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
