# Generated by Django 3.0.14 on 2021-07-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence_sys', '0004_auto_20210726_0301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendence',
            old_name='branch',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='attendence',
            old_name='section',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='attendence',
            name='Faculty_Name',
        ),
        migrations.AddField(
            model_name='attendence',
            name='faculty',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
